name: Deploy to AWS

on:
  push:
    branches:
      - main # triggers on push to main branch
    
    paths:
      - 'src/**'
      - 'terraform/**'
      - 'models/**'
      - 'Dockerfile'
      - 'conda-linux-64.lock'
      - '.github/workflows/deploy.yml'
    

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: audio-predictive-maintenance
  TF_WORKING_DIR: './terraform'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      # free up disk space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      # configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # build, tag, and push docker image
      - name: Build, Tag, and Push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} # git commit hash as unique tag
        run: |
          echo "Building image..."
          docker build --platform linux/amd64 --provenance=false -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          echo "Pushing image..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # setup terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # terraform init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"